name: Load Data to Database

# on:
#   schedule:
#     - cron: '0 0 * * *' # Runs daily at midnight UTC
on: push # test the workflow to make sure it runs

permissions:
  contents: write-all

jobs:
  update-records:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Pull Data and Load to DB
      run: python db_load_data.py
